# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    metallb-config.yaml                                :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: lejulien <lejulien@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/01/25 09:04:51 by lejulien          #+#    #+#              #
#    Updated: 2021/02/03 14:51:01 by lejulien         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: ConfigMap
metadata:
        namespace: metallb-system
        name: config
data:
        config: |
            address-pools:
             - name: default
               protocol: layer2
               addresses:
                -192.168.49.3-192.168.49.10
