apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mariadb
  name: mariadb-volume
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  annotations: 
    metallb.universe.tf/allow-shared-ip : nginx
spec:
  ports:
  - name: https
    port: 3306
    targetPort: 3306
    protocol: TCP
  selector:
    app: mariadb
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deploy
spec:
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: my_mysql:latest
        imagePullPolicy: "Never"
        ports:
        - name: https
          containerPort: 3306
        volumeMounts:
        - name: mariadb-persistent-storage
          mountPath: /var/lib/mysql
      livenessProbe:
        exec:
          command:
            - /bin/sh
            - -c
            - echo 'SHOW DATABASES;' | mysql | grep wordpress
          initialDelaySeconds: 30
          periodSeconds: 3
      volumes:
      - name: mariadb-persistent-storage
        persistentVolumeClaim:
          claimName: mariadb-volume
      hostname: mariadb
