apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: sharing key
spec:
  type: LoadBalancer
  selector:
    app: wordpress
  ports:
  - port: 5050
    targetPort: 5050
    protocol: TCP
    name: https

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: my_wordpress
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
          #livenessProbe:
          #exec:
          #  command:
          #    - /bin/sh
          #    - -c
          #    - ps aux | grep -v grep | grep "php-fpm" && ps aux | grep -v grep | grep "nginx"
          #initialDelaySeconds: 3
          #periodSeconds: 3
