apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    peers:
      peer-address: 10.0.0.1
      peer-asn: 64512
      my-asn: 64512
      peer-port: 179
      hold-time: 120s
      router-id: 1.2.3.4
      password: "yourPassword"
      node-selectors:
        match-labels:
          kubernetes.io/hostname: prod-01
        match-expressions:
        - key: beta.kubernetes.io/arch
          operator: In
          values: [amd64, arm]
    address-pools:
      name: my-ip-space
      protocol: bgp
      addresses:
      - 198.51.100.0/24
      - 192.168.0.150-192.168.0.200
      avoid-buggy-ips: true
      auto-assign: false
      bgp-advertisements:
        aggregation-length: 32
        localpref: 100
        communities:
        - 64512:1
        - no-export
    bgp-communities:
      no-export: 65535:65281
